//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string Ar_Name { get; set; }
        public string En_Name { get; set; }
        public float Price { get; set; }
        public Nullable<double> Discount { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public int Quantity { get; set; }
        public string Image { get; set; }
        public int SubCategotyId { get; set; }
        public bool Isdeleted { get; set; }
    
        public virtual SubCategory SubCategory { get; set; }
    }
}
